FROM --platform=${TARGETPLATFORM} ghcr.io/jmuchovej/baseimage:metabuilder-latest
ARG TARGETPLATFORM
ARG BUILD_DATE

LABEL MAINTAINER "John Muchovej <jmuchovej@pm.me>" \
      CONTAINER "jmuchovej/baseimage:{{ dockerTag }}"

{%- if versions.python %}
# region Python Setup
USER abc
ENV PYENV_ROOT /usr/local/pyenv
RUN HOME="/home/abc" . /etc/profile.d/01-ensurepath.sh; \
    pipx install pipenv; \
    curl https://pyenv.run | PYENV_ROOT=${PYENV_ROOT} bash; \
    pyenv install {{ versions.python }} 
# endregion
{% endif %}

{%- if versions.julia %}
# region Julia Setup
USER abc
RUN HOME="/home/abc" . /etc/profile.d/01-ensurepath.sh; \
    curl -fsSL https://install.julialang.org | sh -s -- --yes --default-channel {{ versions.julia }}; \
# endregion
{% endif %}

{%- if versions.rbase %}
# region R Setup
USER root
RUN apt install \
        r-base={{ versions.rbase }}-* \
        r-base-dev={{ versions.rbase }}-* \
            r-base-core={{ versions.rbase }}-* \
        r-recommended={{ versions.rbase }}-* \
    ; \
    rm -rf /var/lib/apt/lists/*; \
    apt clean;
# endregion
{% endif %}

{%- if versions.node %}
# region Node.js Setup
USER abc
ENV NVM_DIR /usr/local/nvm
RUN HOME="/home/abc" . /etc/profile.d/01-ensurepath.sh; \
    curl -o- https://github.com/nvm-sh/nvm/raw/master/install.sh | NVM_DIR=${NVM_DIR} bash; \
    . ${NVM_DIR}/nvm.sh; \
    nvm install {{ versions.node }}; \
    nvm alias default {{ versions.node }}; \
    nvm use default
# endregion
{% endif -%}
