#!/usr/bin/with-contenv zsh

# function update() {
#     file="${1}"
#     update="n"
#     if [ -f ${file} ]; then
#         echo "Detected \`${file}\`, update environment? [y/N] "
#         read update
#         update="$(echo ${update:0:1} | tr -d "[:upper:]" "[:lower:]")"
#     fi
#     echo "${update}"
# }
#
# container=$(echo ${CONTAINER} | cut -d ":" -f 1)
# case "${container}" in
#     "jmuchovej/julia")
#         file="/workspace/Project.toml"
#         if [ "$(update ${file})" == "y"]; then
#             cp ${file} ${JULIA_DEPOT_PATH}/environments/base/Project.toml
#             julia -O3 /app/install.jl
#         fi
#         ;;
#     "jmuchovej/conda"|"jmuchovej/python")
#         file="/workspace/env.yml"
#         if [ "$(update ${file})" == "y" ]; then
#             cp ${file} /root/env.yml
#             conda env update -n base -f ${file}
#         fi
#         ;;
# esac
