#!/usr/bin/env zsh

case "${1}" in
    "kernel")
        connection_file=${2}
        cat ${connection_file}

        # Modify the damn connection file to use proper IP address now
        sed -i 's;127.0.0.1;0.0.0.0;' ${connection_file}

        /app/kernel ${connection_file}
        ;;
    "lab"|"notebook")
        echo "Already running as a background service. Exiting..."
        exit 0
        ;;
    "sh"|"bash"|"zsh"|"shell")
        /usr/bin/zsh
        ;;
    "-h"|"--help")
        echo "Usage: docker [ARGS] ${IMAGE_NAME} [<command>] ..."
        echo "Valid <command>s are:"
        echo "  kernel            Launches a Jupyter Kernel within the container."
        echo "  lab|notebook      Launches a Jupyter Lab server iff not already started."
        echo "  zsh|sh|bash|shell Drops you into a Bash Shell."
        echo "  *                 Expects a valid program file, which will be prefixed by the /path/to/language"
        exit 0
        ;;
    "")
        while true; do
            sleep 1
        done
        ;;
    *)
        /app/language ${@}
        ;;
esac
